Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,25 +29,24 @@ jobs:
     - name: Check if Lambda function exists and create it if not
       run: |
         FUNCTION_NAME="lambda"
-        FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region AWS_REGION --query 'Configuration.FunctionName' --output text || echo "Not Found")
-        
+        FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region eu-north-1 --query 'Configuration.FunctionName' --output text || echo "Not Found")
+
         if [ "$FUNCTION_EXISTS" == "Not Found" ]; then
-          ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
           echo "Lambda function does not exist. Creating Lambda function..."
           aws lambda create-function \
             --function-name $FUNCTION_NAME \
             --runtime python3.9 \
-            --role arn:aws:iam::$ACCOUNT_ID:role/LambdaExecutionRole \
+            --role arn:aws:iam::732498778071:role/demotest-role-dk8nvxma \
             --handler lambda_function.lambda_handler \
             --zip-file fileb://lambda_function.zip \
-            --region AWS_REGION
+            --region eu-north-1
         else
           echo "Lambda function already exists."
         fi
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: ${{ secrets.REGION}}
+        AWS_REGION: eu-north-1
 
     - name: Deploy Lambda function code with retry
       run: |
@@ -59,7 +58,7 @@ jobs:
           aws lambda update-function-code \
             --function-name lambda \
             --zip-file fileb://lambda_function.zip \
-            --region AWS_REGION && SUCCESS=true && break
+            --region eu-north-1 && SUCCESS=true && break
           RETRY_COUNT=$(($RETRY_COUNT + 1))
           echo "Waiting for Lambda function to be ready..."
           sleep $((2 ** $RETRY_COUNT))  # Exponential backoff
@@ -71,7 +70,7 @@ jobs:
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: ${{ secrets.REGION}}
+        AWS_REGION: eu-north-1
 
     - name: Configure environment variables with retry
       run: |
@@ -83,7 +82,7 @@ jobs:
           aws lambda update-function-configuration \
             --function-name lambda \
             --environment "Variables={HEROKU_API_KEY=value1,HOSTED_ZONE_ID=value2,SENDER_MAIL=value3,RECEIVER_MAIL=receviver_mail,SLACK_URL=value4,HEROKU_APP_NAME=value5,CERTIFICATE_NAME=tyrannosaurs-28703,}" \
-            --region AWS_REGION && SUCCESS=true && break
+            --region eu-north-1 && SUCCESS=true && break
           RETRY_COUNT=$(($RETRY_COUNT + 1))
           echo "Waiting for Lambda function to be ready..."
           sleep $((2 ** $RETRY_COUNT))  # Exponential backoff
@@ -95,4 +94,5 @@ jobs:
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: ${{ secrets.REGION}}
+        AWS_REGION: eu-north-1
+
