Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,7 +29,7 @@ jobs:
     - name: Check if Lambda function exists and create it if not
       run: |
         FUNCTION_NAME="lambda"
-        FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region us-east-1 --query 'Configuration.FunctionName' --output text || echo "Not Found")
+        FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region ${{ vars.REGION }} --query 'Configuration.FunctionName' --output text || echo "Not Found")
         
         RETRY_COUNT=0
         MAX_RETRIES=5
@@ -37,14 +37,15 @@ jobs:
 
         while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
           if [ "$FUNCTION_EXISTS" == "Not Found" ]; then
+            ACCOUNT_ID=$(aws sts get-caller-identity --query "Account" --output text)
             echo "Lambda function does not exist. Creating Lambda function..."
             aws lambda create-function \
               --function-name $FUNCTION_NAME \
               --runtime python3.9 \
-              --role arn:aws:iam::732498778071:role/testinspect \
+              --role arn:aws:iam::$ACCOUNT_ID:role/${{ vars.ROLE }} \
               --handler lambda_function.lambda_handler \
               --zip-file fileb://lambda_function.zip \
-              --region us-east-1 && SUCCESS=true && break
+              --region ${{ vars.REGION }} && SUCCESS=true && break
           else
             echo "Lambda function already exists."
             SUCCESS=true
@@ -63,7 +64,7 @@ jobs:
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: us-east-1
+        AWS_REGION: ${{ vars.REGION }}
 
     - name: Deploy Lambda function code with retry
       run: |
@@ -75,7 +76,7 @@ jobs:
           aws lambda update-function-code \
             --function-name lambda \
             --zip-file fileb://lambda_function.zip \
-            --region us-east-1 && SUCCESS=true && break
+            --region ${{ vars.REGION }} && SUCCESS=true && break
           RETRY_COUNT=$(($RETRY_COUNT + 1))
           echo "Waiting for Lambda function to be ready..."
           sleep $((2 ** $RETRY_COUNT))  # Exponential backoff
@@ -87,7 +88,7 @@ jobs:
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: us-east-1
+        AWS_REGION: ${{ vars.REGION }}
 
     - name: Configure environment variables with retry
       run: |
@@ -99,7 +100,7 @@ jobs:
           aws lambda update-function-configuration \
             --function-name lambda \
             --environment "Variables={HEROKU_API_KEY=value1,HOSTED_ZONE_ID=value2,SENDER_MAIL=value3,RECEIVER_MAIL=receviver_mail,SLACK_URL=value4,HEROKU_APP_NAME=value5,CERTIFICATE_NAME=tyrannosaurs-28703,}" \
-            --region us-east-1 && SUCCESS=true && break
+            --region ${{ vars.REGION }} && SUCCESS=true && break
           RETRY_COUNT=$(($RETRY_COUNT + 1))
           echo "Waiting for Lambda function to be ready..."
           sleep $((2 ** $RETRY_COUNT))  # Exponential backoff
@@ -111,4 +112,5 @@ jobs:
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION: us-east-1
+        AWS_REGION: ${{ vars.REGION }}
+        
