Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -30,18 +30,35 @@ jobs:
       run: |
         FUNCTION_NAME="lambda"
         FUNCTION_EXISTS=$(aws lambda get-function --function-name $FUNCTION_NAME --region us-east-1 --query 'Configuration.FunctionName' --output text || echo "Not Found")
+        
+        RETRY_COUNT=0
+        MAX_RETRIES=5
+        SUCCESS=false
 
-        if [ "$FUNCTION_EXISTS" == "Not Found" ]; then
-          echo "Lambda function does not exist. Creating Lambda function..."
-          aws lambda create-function \
-            --function-name $FUNCTION_NAME \
-            --runtime python3.9 \
-            --role arn:aws:iam::732498778071:role/inspectpointtemp \
-            --handler lambda_function.lambda_handler \
-            --zip-file fileb://lambda_function.zip \
-            --region us-east-1
-        else
-          echo "Lambda function already exists."
+        while [[ $RETRY_COUNT -lt $MAX_RETRIES ]]; do
+          if [ "$FUNCTION_EXISTS" == "Not Found" ]; then
+            echo "Lambda function does not exist. Creating Lambda function..."
+            aws lambda create-function \
+              --function-name $FUNCTION_NAME \
+              --runtime python3.9 \
+              --role arn:aws:iam::732498778071:role/inspectpointtemp \
+              --handler lambda_function.lambda_handler \
+              --zip-file fileb://lambda_function.zip \
+              --region us-east-1 && SUCCESS=true && break
+          else
+            echo "Lambda function already exists."
+            SUCCESS=true
+            break
+          fi
+          
+          RETRY_COUNT=$(($RETRY_COUNT + 1))
+          echo "Waiting before retrying..."
+          sleep $((2 ** $RETRY_COUNT))  # Exponential backoff
+        done
+
+        if [ "$SUCCESS" = false ]; then
+          echo "Failed to create Lambda function after $MAX_RETRIES attempts."
+          exit 1
         fi
       env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -95,4 +112,3 @@ jobs:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: us-east-1
-
